schema = 3

[mod]
  [mod."github.com/klauspost/compress"]
    version = "v1.15.9"
    hash = "sha256-ctPxlVq0c/SoNPVsP66RjxUjTHys3diW2Apxjyc9WdE="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.15"
    hash = "sha256-OJCDsZuNUxCLrNRZmnpRpo5clcaasPiUdgWtoVxiA1Y="
  [mod."github.com/segmentio/kafka-go"]
    version = "v0.4.47"
    hash = "sha256-mebYAZ591RkOetzWSJHRDIM16HDzJ2KqEzMvq9gOI3I="
